name = "MyWorkflow"
uuid = "7abf360e-92cb-4f35-becd-441c2614658a"
authors = ["Satoshi Terasaki <terasakisatoshi.math@gmail.com>"]
version = "0.10.1"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DiffEqFlux = "aae7a2af-3d4f-5e19-a356-7da93b79d9d0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Example = "7876af07-990d-54b4-ab0e-23690620f79a"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
ImageShow = "4e3cecfd-b093-5904-9786-8bbb286a6a31"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
ORCA = "47be7bcc-f1a6-5447-8b36-7eeeff7534fd"
OhMyREPL = "5fb14364-9ced-5910-84b2-373655c76a03"
Plotly = "58dd65bb-95f3-509e-9936-c39a10fdeae7"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
SymEngine = "123dc426-2d89-5057-bbad-38513e3affd8"
SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
WebIO = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
Colors = "0.12"
Combinatorics = "1.0"
DiffEqFlux = "1.8"
DifferentialEquations = "6.13"
Distributions = "0.22, 0.23"
Example = "= 0.5.1, 0.5"
ForwardDiff = "0.10"
GR = "0.49"
HDF5 = "0.13"
IJulia = "1.21"
ImageFiltering = "0.6"
ImageMagick = "1.1"
ImageShow = "0.2"
Images = "0.22"
Interact = "0.10"
LaTeXStrings = "1.0"
MLDatasets = "0.5"
ORCA = "0.3"
OhMyREPL = "0.5"
Plotly = "0.3"
PlotlyJS = "0.13"
Plots = "1.3"
Revise = "2.6"
Rotations = "0.13, 1.0"
SpecialFunctions = "0.10"
StaticArrays = "0.12"
StatsPlots = "0.14"
SymEngine = "0.8"
SymPy = "1.0"
TestImages = "1.0"
Turing = "=0.12"
Zygote = "0.4"
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
