name = "MyWorkflow"
uuid = "7abf360e-92cb-4f35-becd-441c2614658a"
authors = ["Satoshi Terasaki <terasakisatoshi.math@gmail.com>"]
version = "0.24.0"

[deps]
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Example = "7876af07-990d-54b4-ab0e-23690620f79a"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
ImageShow = "4e3cecfd-b093-5904-9786-8bbb286a6a31"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
JSExpr = "97c1335a-c9c5-57fe-bc5d-ec35cebe8660"
JSXGraph = "97e4c2e4-f0cb-461e-a268-312dec255b76"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LazySets = "b4f0291d-fe17-52bc-9479-3d1a343d9043"
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJLinearModels = "6ee0df7b-362f-4a72-a706-9e79364fb692"
MetaUtils = "ed17dc9e-20eb-4460-9701-8d0520e45e1f"
ORCA = "47be7bcc-f1a6-5447-8b36-7eeeff7534fd"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
OhMyREPL = "5fb14364-9ced-5910-84b2-373655c76a03"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
Pandas = "eadc2687-ae89-51f9-a5d9-86b5a6373a9c"
Plotly = "58dd65bb-95f3-509e-9936-c39a10fdeae7"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
Random123 = "74087812-796a-5b5d-8853-05524746bad3"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
ScikitLearn = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
Seaborn = "d2ef9438-c967-53ab-8060-373fdd9e13eb"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
SymEngine = "123dc426-2d89-5057-bbad-38513e3affd8"
SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"
Tulip = "6dd1b50a-3aae-11e9-10b5-ef983d2400fa"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
WAV = "8149f6b0-98f6-5db9-b78f-408fbbb8ef88"
WebIO = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
ArrayInterface = "2.14.17, 3.1"
BenchmarkTools = "0.5.0, 0.7, 1.0"
CSV = "0.8.4"
Colors = "0.12.6"
Combinatorics = "1.0.2"
DataFrames = "0.22.6, 1.1"
DifferentialEquations = "6.16.0"
Distributions = "0.23.8, 0.25"
Example = "0.5.3"
FillArrays = "0.8.14, 0.11"
ForwardDiff = "0.10.17"
GR = "0.55.0, 0.57"
Glob = "1.3.0"
IJulia = "1.23.2"
ImageFiltering = "0.6.20"
ImageMagick = "1.2.0"
ImageShow = "0.2.3, 0.3"
Images = "0.23.3, 0.24"
Interact = "0.10.3"
JSExpr = "0.5.2, 1.0"
JSXGraph = "0.1.6"
JuMP = "0.21.4"
LaTeXStrings = "1.2.1"
LazySets = "1.43.2"
Luxor = "2.10.0"
MLDatasets = "0.5.5"
MLJ = "0.16.0"
MLJLinearModels = "0.5.3"
MetaUtils = "0.1.5"
ORCA = "0.5.0"
OffsetArrays = "1.6.2"
OhMyREPL = "0.5.10"
PackageCompiler = "1.2.5"
Pandas = "1.4.0"
Plotly = "0.3.0, 0.4"
PlotlyJS = "0.14.1"
Plots = "1.11.0"
Pluto = "0.12.21, 0.14"
PlutoUI = "0.7.1"
PyCall = "1.92.2"
PyPlot = "2.9.0"
RCall = "0.13.10"
Random123 = "1.3.1"
Revise = "3.1.14"
Rotations = "1.0.2"
ScikitLearn = "0.6.3"
Seaborn = "0.4.1"
SpecialFunctions = "0.10.3, 1.3"
StaticArrays = "0.12.5, 1.1"
StatsBase = "0.33.4"
StatsPlots = "0.14.19"
SymEngine = "0.8.3"
SymPy = "1.0.41"
TestImages = "1.4.0"
Tulip = "0.7.3"
UnicodePlots = "1.3.0, 2.1"
WAV = "1.1.0"
WebIO = "0.8.15"
Zygote = "0.5.17, 0.6"
julia = "1.5"

[extras]
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Glob"]
